name: network_calling
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  intl: ^0.18.0
  json_serializable: ^6.7.0

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0


flutter:
  uses-material-design: true
  generate: true
