name: flutter_template
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  auto_route: ^11.1.0
  bloc: ^9.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  google_fonts: ^8.1.0
  injectable: ^3.0.0
  injectable_generator: ^3.0.2
  intl: ^0.20.2
  freezed: ^3.2.5
  json_annotation: ^4.11.0
  logger: ^2.7.0
  flutter_secure_storage: ^10.1.0
  mocktail: ^1.0.5
  dio: ^5.9.2
  retrofit: ^4.9.2
  gap: ^3.0.1
  auto_size_text: ^3.0.0
  flutter_svg: ^2.3.0
  flutter_lints: ^6.0.0
  shared_preferences: ^2.5.5
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^7.1.1
  flutter_gen: ^5.14.1
  webview_flutter: ^4.13.1
  url_launcher: ^6.3.2


dev_dependencies:
  auto_route_generator: ^10.5.0
  build_runner: ^2.15.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.13.2
  retrofit_generator: ^10.2.6
  flutter_gen_runner: ^5.14.1
  very_good_analysis: ^10.2.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
