name: network_calling
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.2.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  http: ^1.0.0
  injectable: ^2.1.1
  intl: ^0.18.0
  json_serializable: ^6.7.0
  logger: ^1.4.0
  retrofit: ^4.0.1

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  mocktail: ^0.3.0
  retrofit_generator: ^7.0.1
  very_good_analysis: ^5.0.0


flutter:
  uses-material-design: true
  generate: true
