// Mocks generated by Mockito 5.4.2 from annotations
// in network_calling/test/data/data_sources/public_api/remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:network_calling/data/data_sources/public_api/remote_data_sources.dart'
    as _i3;
import 'package:network_calling/data/response_objects/public_api/public_api_response.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePublicApiResponse_0 extends _i1.SmartFake
    implements _i2.PublicApiResponse {
  _FakePublicApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteDataSources].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSources extends _i1.Mock implements _i3.RemoteDataSources {
  @override
  _i4.Future<_i2.PublicApiResponse> getAllApi() => (super.noSuchMethod(
        Invocation.method(
          #getAllApi,
          [],
        ),
        returnValue:
            _i4.Future<_i2.PublicApiResponse>.value(_FakePublicApiResponse_0(
          this,
          Invocation.method(
            #getAllApi,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.PublicApiResponse>.value(_FakePublicApiResponse_0(
          this,
          Invocation.method(
            #getAllApi,
            [],
          ),
        )),
      ) as _i4.Future<_i2.PublicApiResponse>);
}
