// Mocks generated by Mockito 5.4.2 from annotations
// in network_calling/test/domain/usecase/get_api_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:network_calling/domain/entities/api/api_entity.dart' as _i4;
import 'package:network_calling/domain/services/public_api/public_api_services.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PublicApiServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockPublicApiServices extends _i1.Mock implements _i2.PublicApiServices {
  @override
  _i3.Future<List<_i4.ApiEntity>> getAllApi() => (super.noSuchMethod(
        Invocation.method(
          #getAllApi,
          [],
        ),
        returnValue: _i3.Future<List<_i4.ApiEntity>>.value(<_i4.ApiEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.ApiEntity>>.value(<_i4.ApiEntity>[]),
      ) as _i3.Future<List<_i4.ApiEntity>>);
}
